site_name: Cheatsheets
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/logo.png

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://blog.woernfl.xyz/
      name: Woernfl's blog
    - icon: fontawesome/brands/github
      link: https://github.com/woernfl
      name: Woernfl on Github
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/woernfl
      name: Woernfl on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/woernfl
      name: Woernfl on Linkedin